{
    'name': 'baamtu academy',
    'version': '1.0',
    'author': 'ABDOUL AZIZ SY',
    'depends': ['base','website'],
    'category': 'Administration',
    'sequence':-100,
    'description' : "ceci est mon premier module",
    'application':'true',
    'data':[
     'security/ir.model.access.csv',
     'security/security.xml',
     #'data/demo_data_course.xml',
     'data/data.xml',
     #'views/webstudent_registration_template.xml',
     #'views/portal_template.xml',
     'views/course.xml',
     'wizard/registration_wizard.xml',
     'views/professor.xml',
     'views/classroom.xml',
     'views/registration.xml',
     'views/course_registration_report.xml',
     'views/student.xml',
     'views/menuitem.xml',   
     'views/res_partner.xml', 
     #'report/student_card_template.xml',   
     'report/report.xml'
    ],
} 
